#!/usr/bin/env python3
"""Generate the badge marks that curves, not corners, decide.

    .venv/bin/python scripts/gen-badge-marks.py

Prints TypeScript for `lab/src/corpus/badges.ts`. Each shape is built on a
1000-unit grid and sampled densely, then normalized into the unit box the
marks draw in -- placing a dozen bezier control points by eye in that box
could not hold a taper or an arrowhead, and every attempt read as something
else: the horseshoe as a letter U, the brush as a bottle.
"""
from __future__ import annotations

import math
import pathlib

GRID = 500.0  # half-width of the design box; output is divided by this


def arc(cx, cy, r, a0, a1, n):
    return [(cx + r * math.cos(a0 + (a1 - a0) * i / (n - 1)),
             cy + r * math.sin(a0 + (a1 - a0) * i / (n - 1)))
            for i in range(n)]


def horseshoe():
    """A U -- tall, narrow mouth, long limbs. The squares that make it a
    magnet are cut in `badges.ts` in the field color, near the tips and flush
    with the outer edge so the limb stays whole behind them."""
    cy, ro, ri = 110.0, 385.0, 175.0
    tip = -400.0
    # Sampling pi -> 0 passes through pi/2, which in a y-down space is the
    # bottom. pi -> 2*pi passes 3*pi/2 and puts the bend on top, which is an
    # upside-down U with notches in the wrong place.
    pts = [(-ro, tip)]
    pts += arc(0, cy, ro, math.pi, 0, 90)
    pts += [(ro, tip), (ri, tip)]
    pts += arc(0, cy, ri, 0, math.pi, 90)
    pts += [(-ri, tip)]
    return pts


def redo_arrow():
    """The subset sign with a head: one filled band, so the head cannot come
    adrift of the stroke it is supposed to finish."""
    rm, t = 330.0, 78.0
    a0, ah, a1 = math.pi * 0.1, math.pi * 1.62, math.pi * 1.89
    outer = arc(0, 0, rm + t, a0, ah, 70)
    inner = arc(0, 0, rm - t, ah, a0, 70)
    # Base half-width against the chord to the apex, so the head comes out
    # near enough equilateral rather than squat.
    wing = t * 2.0
    head = [(math.cos(ah) * (rm + wing), math.sin(ah) * (rm + wing)),
            (math.cos(a1) * rm, math.sin(a1) * rm),
            (math.cos(ah) * (rm - wing), math.sin(ah) * (rm - wing))]
    return outer + head + inner


def brush():
    """Bristles as a spine that curls at the tip, offset either side by a
    width that goes to nothing. Walking the spine by its heading is what
    makes it curl -- leaning a straight spine sideways only ever produced a
    bent bottle."""
    n, length = 110, 760.0
    step = length / (n - 1)
    x, y, spine, widths = 0.0, 250.0, [], []
    for i in range(n):
        u = i / (n - 1)
        heading = -math.pi / 2 + 1.45 * u ** 2.4
        x += math.cos(heading) * step
        y += math.sin(heading) * step
        spine.append((x, y, heading))
        # Wide at the base so it meets the ferrule squarely, a slight belly,
        # and nothing at all at the tip.
        belly = 0.62 + 0.38 * math.sin(math.pi * u ** 0.75)
        widths.append(max(200.0 * belly * (1.0 - u ** 2.2), 3.0))

    left, right = [], []
    for (px, py, heading), w in zip(spine, widths):
        nx, ny = -math.sin(heading), math.cos(heading)
        left.append((px + nx * w, py + ny * w))
        right.append((px - nx * w, py - ny * w))
    # A rounded base, seated in the ferrule rather than cut flat across it.
    base = arc(0, spine[0][1], widths[0], math.pi, 0, 24)
    # Not recentered on its own bounding box: the ferrule is drawn at x = 0,
    # and the curl would drag the base off it.
    return left + list(reversed(right)) + base


HEADER = """/* Generated by scripts/gen-badge-marks.py -- do not edit by hand.
 *
 * Flat x,y pairs in the unit box the badge marks draw in, sampled densely
 * from the shapes that script builds. The curve is the whole cue: placed by
 * hand in this box the horseshoe read as a letter U and the brush as a
 * bottle.
 */

"""


def minifig():
    """`3626b`'s own outline seen face on -- its triangles and its analytic
    cylinders unioned, then resampled at a fine step. Simplified coarsely it
    facets, which is the tessellation the OCCT engine exists to avoid, and it
    shows on a dome at badge size."""
    import numpy as np
    from shapely.geometry import Polygon, box
    from shapely.ops import unary_union
    from brick_icons import hlr

    roots = hlr.default_roots("vendor/ldraw")
    out = {"2": [], "5": [], "tri": [], "tri_meta": [], "analytic": []}
    hlr.flatten(hlr._resolve_input("3626b", roots), np.eye(3), np.zeros(3), out, roots)
    polys = []
    for t in np.array(out["tri"]):
        poly = Polygon([(float(v[0]), float(v[1])) for v in t])
        if poly.area > 1e-7:
            polys.append(poly if poly.is_valid else poly.buffer(0))
    for prim in out["analytic"]:
        R, t = np.asarray(prim.R), np.asarray(prim.t)
        rx, h, y0, x0 = abs(R[0, 0]), abs(R[1, 1]), float(t[1]), float(t[0])
        if type(prim).__name__ == "Cylinder":
            polys.append(box(x0 - rx, y0, x0 + rx, y0 + h))
    shape = unary_union(polys).buffer(0.3).buffer(-0.3)
    if shape.geom_type == "MultiPolygon":
        shape = max(shape.geoms, key=lambda g: g.area)
    ring = shape.simplify(0.06).exterior
    # Resample at a fixed step so the dome carries points where it curves.
    step = 0.9
    n = max(120, int(ring.length / step))
    pts = [ring.interpolate(i / n, normalized=True).coords[0] for i in range(n)]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    half = max(max(xs) - min(xs), max(ys) - min(ys)) / 2
    return [((x - cx) / half * GRID, (y - cy) / half * GRID) for x, y in pts]


def contract(pts, inset, keep):
    """The shape's own outline pulled inward, then clipped to `keep`.

    A cutout shaped like an axis-aligned rectangle reads as damage; one that
    is the silhouette contracted reads as a marking on the form.
    """
    from shapely.geometry import Polygon

    inner = Polygon(pts).buffer(-inset, join_style=2)
    if inner.is_empty:
        return []
    hit = inner.intersection(keep)
    parts = list(hit.geoms) if hit.geom_type == "MultiPolygon" else [hit]
    return [list(part.exterior.coords) for part in parts if not part.is_empty]


def emit_many(name, groups):
    rows = []
    for pts in groups:
        flat = []
        for x, y in pts:
            flat += [f"{x / GRID:.4f}", f"{y / GRID:.4f}"]
        body = ", ".join(flat)
        rows.append(f"  [{body}]")
    joined = ",\n".join(rows)
    return f"export const {name}: number[][] = [\n{joined},\n];\n"


def emit(name, pts):
    flat = []
    for x, y in pts:
        flat += [f"{x / GRID:.4f}", f"{y / GRID:.4f}"]
    rows = [", ".join(flat[i:i + 8]) for i in range(0, len(flat), 8)]
    body = ",\n  ".join(rows)
    return f"export const {name}: number[] = [\n  {body},\n];\n"


if __name__ == "__main__":
    out = [HEADER]
    for name, fn in (("MAGNET", horseshoe), ("REDO", redo_arrow),
                     ("BRUSH", brush), ("MINIFIG", minifig)):
        pts = fn()
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        print(f"{name}: {len(pts)} points, "
              f"x {min(xs) / GRID:.2f}..{max(xs) / GRID:.2f} "
              f"y {min(ys) / GRID:.2f}..{max(ys) / GRID:.2f}")
        out.append(emit(name, pts))
    from shapely.geometry import Point, box as sbox

    magnet_pts = horseshoe()
    tip = -470.0
    cuts = contract(magnet_pts, 34.0, sbox(-GRID, -400.0, GRID, -400.0 + 190.0))
    out.append(emit_many("MAGNET_CUT", cuts))
    print(f"MAGNET_CUT: {len(cuts)} pieces")

    brush_pts = brush()
    tip_xy = brush_pts[len(brush_pts) // 2 - 1]
    cuts = contract(brush_pts, 26.0, Point(tip_xy).buffer(250.0))
    out.append(emit_many("BRUSH_CUT", cuts))
    print(f"BRUSH_CUT: {len(cuts)} pieces")

    dest = pathlib.Path(__file__).resolve().parent.parent / "lab/src/corpus/markPaths.ts"
    dest.write_text("\n".join(out))
    print(f"wrote {dest}")
